import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/components/AuthProvider";

export const metadata: Metadata = {
    title: "Ruciloss App | Login",
    description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/theme-provider";

type RootLayoutProps = {
    children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <>
            <html lang="en" dir="ltr" suppressHydrationWarning>
                <head></head>
                <body>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <AuthProvider>{children}</AuthProvider>
                    </ThemeProvider>
                </body>
            </html>
        </>
    );
}
